### PR TITLE
Doip improvements

### PR DESCRIPTION
**Pull request by ferdinandjarisch**
Generic DoIP-related stuff.

See individual commits for changes...

### CODE REVIEW

**Comment by rumpelsepp** [comment]
I looked through your changes, looks good. 
Why did you remove https://github.com/Fraunhofer-AISEC/gallia/pull/435/commits/ac2622758dec95f6482d27d257b25ddaae5085fc#diff-f660a710f16526600ee2030ded239303921184cb7f83fe263bce71c5e843f132L107 this?
I copied the package definitions from the standard, so I figure it should be there even when it is currently unused.

**Comment by ferdinandjarisch** [comment]
> Why did you remove [ac26227#diff-f660a710f16526600ee2030ded239303921184cb7f83fe263bce71c5e843f132L107](https://github.com/Fraunhofer-AISEC/gallia/commit/ac2622758dec95f6482d27d257b25ddaae5085fc#diff-f660a710f16526600ee2030ded239303921184cb7f83fe263bce71c5e843f132L107) this?

While the "PayloadTypeSpecificMessageContent" is part of the DoIP packet, it is not part of the GenericHeader; it actually follows after the GenericHeader, as effective **payload** of the packet.

It does not make sense to have this field in the GenericHeader, and obviously it was never used anyhow.

**Comment by rumpelsepp** [comment]
Ah. Ok.

**Review by rumpelsepp — APPROVED** [review]

**Comment by ferdinandjarisch** [comment]
I will give this another test run on Monday and if successful will press merge.

Thanks a lot! :)

**Comment by ferdinandjarisch** [comment]
@rumpelsepp 

Tested and looks good to me.

I added another three commits on top; if those are fine with you, go ahead and merge!

**Pull request merged**
